name: Enable GitHub Pages

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  enable-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Enable GitHub Pages
        run: |
          git checkout main  # Adjust the branch name as needed
          git remote set-head origin -a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
